//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermarket.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_stock
    {
        public int id { get; set; }
        public double quantity { get; set; }
        public System.DateTime supply_date { get; set; }
        public System.DateTime expiration_date { get; set; }
        public double purchase_price { get; set; }
        public double selling_price { get; set; }
        public int product_id { get; set; }
        public int unit_id { get; set; }
        public bool active { get; set; }
    
        public virtual measuring_unit measuring_unit { get; set; }
        public virtual product product { get; set; }
    }
}
