//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermarket.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class receipt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public receipt()
        {
            this.sold_products = new HashSet<sold_products>();
        }
    
        public int id { get; set; }
        public System.DateTime release_date { get; set; }
        public Nullable<double> total { get; set; }
        public int user_id { get; set; }
        public bool active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<sold_products> sold_products { get; set; }
        public virtual user user { get; set; }
    }
}
