//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Supermarket.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class stocks_products
    {
        public double quantity { get; set; }
        public System.DateTime supply_date { get; set; }
        public System.DateTime expiration_date { get; set; }
        public string product_name { get; set; }
        public string bar_code { get; set; }
        public int category_id { get; set; }
        public int producer_id { get; set; }
        public bool product_active { get; set; }
        public int product_id { get; set; }
        public double selling_price { get; set; }
        public int unit_id { get; set; }
        public int product_id_stock { get; set; }
        public bool stock_active { get; set; }
        public double purchase_price { get; set; }
        public int stock_id { get; set; }
    }
}
